#!/bin/sh

if [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
  DOCKER_ARGS="$(cat <<EOA
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_DEFAULT_REGION
EOA
)"
  echo "Using env variables for AWS creds"
else
  DOCKER_ARGS="-v $HOME/.aws/:/root/.aws:ro -e AWS_PROFILE=$AWS_PROFILE"
  echo "Using ~/.aws creds"
fi
  
exec docker run --rm -v "$(pwd)":/workspace "$DOCKER_ARGS" \
  joshmahowald/kitchen-terraform "$@"
