require 'rspec/core/rake_task'

spec_dir=File.dirname(__FILE__)
RSpec::Core::RakeTask.new('spec') do |task|
  
    base_specs        = Dir["#{spec_dir}/*_spec.rb"]
    module_specs     =  Dir["#{spec_dir}/**/*_spec.rb"]
  
    all_specs = base_specs + module_specs
  
    task.pattern = all_specs.join(',')
  end
